Using PHOBODTB;
DELIMITER $$
CREATE PROCEDURE friend (IN p_id INT, IN stat ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED'))
BEGIN
    SELECT USER_ID, CONCAT_WS(' ', FIRST_NAME, LAST_NAME) AS NAME, F.CREATED_AT AS CREATED_AT
    FROM USERS U JOIN FRIENDSHIPS F ON USER_ID = SENDER_ID
    WHERE F.STATUS = stat AND RECEIVER_ID = p_id
    UNION
    SELECT USER_ID, CONCAT_WS(' ', FIRST_NAME, LAST_NAME) AS NAME, F.CREATED_AT AS CREATED_AT
    FROM USERS U JOIN FRIENDSHIPS F ON USER_ID = RECEIVER_ID
    WHERE F.STATUS = stat AND SENDER_ID = p_id
    ORDER BY CREATED_AT DESC;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE count_ver_group (IN p_date DATETIME)
BEGIN
    SELECT G.GROUP_ID, G.NAME, G.CREATED_AT, COUNT(*) AS TOTAL_VERIFIED
    FROM GROUPS G JOIN MEMBERSHIPS M ON G.GROUP_ID = M.GROUP_ID JOIN VERIFIED_USERS V ON M.USER_ID = V.USER_ID
    WHERE G.CREATED_AT > p_date
    GROUP BY G.GROUP_ID
    ORDER BY TOTAL_VERIFIED DESC;
END $$
DELIMITER ;