

SET FOREIGN_KEY_CHECKS = 0;

-- Constraint: age must be > 18
-- Derived attribute: age
CREATE TABLE IF NOT EXISTS `USER` (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    GENDER ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PHONE_NUMBER VARCHAR(20) UNIQUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CONSTRAINT check_phone CHECK (LENGTH(PHONE_NUMBER) = 10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS USER_PROFILE (
    PROFILE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BIO TEXT,
    COVER_PAGE_URL VARCHAR(255),
    AVATAR_URL VARCHAR(255),
    USER_ID BIGINT NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ADMIN` (
    USER_ID BIGINT PRIMARY KEY,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADMIN_LEVEL INT NOT NULL,
    CONSTRAINT chk_admin_level CHECK (ADMIN_LEVEL >= 1 AND ADMIN_LEVEL <= 5),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VERIFIED_USER (
    USER_ID BIGINT PRIMARY KEY,
    VERIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- If A -> B is in table, B -> A is not in table.
CREATE TABLE IF NOT EXISTS FRIENDSHIP (
    SENDER_ID BIGINT,
    RECEIVER_ID BIGINT,
    STATUS ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED') DEFAULT 'PENDING',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SENDER_ID, RECEIVER_ID),
    CONSTRAINT chk_friendships_distinct CHECK (sender_id <> receiver_id),
    FOREIGN KEY (SENDER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `GROUP` (
    GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION TEXT,
    OWNER_ID BIGINT NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS POST (
    POST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    VISIBILITY ENUM('PUBLIC', 'FRIENDS_ONLY', 'PRIVATE') DEFAULT 'PUBLIC',
    CONTENT TEXT,
    USER_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VERIFICATION_DOCS (
    USER_ID BIGINT,
    DOCUMENT_URL VARCHAR(255),
    STATUS ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    PRIMARY KEY (USER_ID, DOCUMENT_URL, STATUS),
    FOREIGN KEY (USER_ID) REFERENCES VERIFIED_USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS GROUP_RULE (
    GROUP_ID BIGINT,
    RULE_ID INT AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY (GROUP_ID, RULE_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUP`(GROUP_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Owner has to be group member
CREATE TABLE IF NOT EXISTS MEMBERSHIP (
    GROUP_ID BIGINT,
    USER_ID BIGINT,
    JOINED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GROUP_ID, USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUP`(GROUP_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Need to ensure that parent post id is not in post id
CREATE TABLE IF NOT EXISTS SHARED_POST (
    POST_ID BIGINT PRIMARY KEY,
    PARENT_POST_ID BIGINT NOT NULL,
    CONSTRAINT chk_shared_posts_not_self CHECK (post_id <> parent_post_id),
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TAG (
    USER_ID BIGINT,
    POST_ID BIGINT,
    PRIMARY KEY (USER_ID, POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS REACT (
    USER_ID BIGINT,
    POST_ID BIGINT,
    REACT_TYPE ENUM('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY'),
    PRIMARY KEY (USER_ID, POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `COMMENT` (
    COMMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONTENT TEXT NOT NULL,
    USER_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS REPORT (
    REPORT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GRANTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS ENUM('PENDING', 'IN_REVIEW', 'RESOLVED', 'DISMISSED') DEFAULT 'PENDING',
    REASON TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    USER_ID BIGINT NOT NULL,
    POST_ID BIGINT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS REVIEW_REPORT (
    REPORT_ID BIGINT,
    ADMIN_ID BIGINT,
    PRIMARY KEY (REPORT_ID, ADMIN_ID),
    FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;