-- Constraint: age must be > 18
-- Derived attribute: age
CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    GENDER ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE,
    PHONE_NUMBER VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CONSTRAINT check_phone CHECK (LENGTH(PHONE_NUMBER) = 10)
);

CREATE TABLE USER_PROFILE (
    PROFILE_ID INT AUTO_INCREMENT PRIMARY KEY,
    BIO TEXT,
    COVER_PAGE_URL VARCHAR(255),
    AVATAR_URL VARCHAR(255),
    USER_ID INT NOT NULL UNIQUE,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE ADMIN (
    USER_ID INT PRIMARY KEY,
    GRANTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    ADMIN_LEVEL INT NOT NULL,
    CONSTRAINT chk_admin_level CHECK (ADMIN_LEVEL >= 1 AND ADMIN_LEVEL <= 5),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE VERIFIED_USER (
    USER_ID INT PRIMARY KEY,
    VERIFIED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- If A -> B is in table, B -> A is not in table.
CREATE TABLE FRIENDSHIP (
    SENDER_ID INT,
    RECEIVER_ID INT,
    STATUS ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED') DEFAULT 'PENDING',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SENDER_ID, RECEIVER_ID),
    FOREIGN KEY (SENDER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (RECEIVER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE `GROUP` (
    GROUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION TEXT,
    OWNER_ID INT NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE POST (
    POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    VISIBILITY ENUM('PUBLIC', 'FRIENDS_ONLY', 'PRIVATE') DEFAULT 'PUBLIC',
    CONTENT TEXT,
    USER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE VERIFICATION_DOCS (
    USER_ID INT,
    DOCUMENT_URL VARCHAR(255),
    STATUS ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    PRIMARY KEY (USER_ID, DOCUMENT_URL, STATUS),
    FOREIGN KEY (USER_ID) REFERENCES VERIFIED_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE GROUP_RULE (
    GROUP_ID INT,
    RULE_ID INT AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY (GROUP_ID, RULE_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUP`(GROUP_ID) ON DELETE CASCADE
);

-- Owner has to be group member
CREATE TABLE MEMBERSHIP (
    GROUP_ID INT,
    USER_ID INT,
    JOINED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GROUP_ID, USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES `GROUP`(GROUP_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

-- Need to ensure that parent post id is not in post id
CREATE TABLE SHARED_POST (
    POST_ID INT PRIMARY KEY,
    PARENT_POST_ID INT,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
);

CREATE TABLE TAG (
    USER_ID INT,
    POST_ID INT,
    PRIMARY KEY (USER_ID, POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
);

CREATE TABLE REACT (
    USER_ID INT,
    POST_ID INT,
    REACT_TYPE ENUM('LIKE', 'LOVE', 'HAHA', 'WOW', 'SAD', 'ANGRY'),
    PRIMARY KEY (USER_ID, POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
);

CREATE TABLE COMMENT (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONTENT TEXT NOT NULL,
    USER_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
);

CREATE TABLE REPORT (
    REPORT_ID INT AUTO_INCREMENT PRIMARY KEY,
    GRANTED_AT DATETIME,
    STATUS ENUM('PENDING', 'IN_REVIEW', 'RESOLVED', 'DISMISSED') DEFAULT 'PENDING',
    REASON TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
);

CREATE TABLE REVIEW_REPORT (
    REPORT_ID INT,
    ADMIN_ID INT,
    PRIMARY KEY (REPORT_ID, ADMIN_ID),
    FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID) ON DELETE CASCADE,
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(USER_ID) ON DELETE CASCADE
);